import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm'],
  // DTS is generated by a separate `tsc --emitDeclarationOnly` step in the
  // build script to avoid rollup-plugin-dts injecting `baseUrl: "."` which
  // TypeScript 6.x deprecated (TS5101).
  dts: false,
  clean: true,
  sourcemap: true,
  target: 'es2020',
  outDir: 'dist',
});
